# Generated by Django 2.2.1 on 2019-06-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.CharField(max_length=255)),
                ('is_code_exist', models.BooleanField()),
            ],
            options={
                'db_table': 'news_site',
            },
        ),
        migrations.CreateModel(
            name='NewsSiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Category')),
                ('news_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.NewsSite')),
            ],
            options={
                'db_table': 'news_site_category',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('category_id', models.IntegerField()),
                ('news_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.NewsSite')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
